qrels = "qrels"
validation_folder = "/lv_local/home/sgregory/robustness/validation/"
score_file = "/lv_local/home/sgregory/robustness/trec_file.txt"
recovery =False
data_set_file ="../svm_test/features"
number_of_folds=5
normalized = False
number_of_competitors = 10
summary_file = "s.txt"