qrels = "qrels"
validation_folder = "validation_ent_pos_minus"
score_file = "trec_file_asr_ent_pos_minus.txt"
recovery =False
data_set_file ="featuresCB_asr"
number_of_folds=5
normalized = True
number_of_competitors = 10
summary_file = "ent_opt_pos_minus.txt"
random_seed = 9001
iter_factor = 1
processes_number = 9
model_handler_file = "model_handler_shrinked_pos_minus.pickle"
gammas = [0.01,0.001,0.0001]